//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vuelo()
        {
            this.PasajeroVueloes = new HashSet<PasajeroVuelo>();
        }
    
        public int IdVuelo { get; set; }
        public string NumeroVuelo { get; set; }
        public string IdOrigen { get; set; }
        public string IdDestino { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
    
        public virtual Destino Destino { get; set; }
        public virtual Origen Origen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasajeroVuelo> PasajeroVueloes { get; set; }
    }
}
